Telegram:
  Error:
    client:
      ChatID: '-1001427728540'
      Token: 5679519420:AAGPFUSm-1gsGXuSnQQfemqrEiCtzXzKUyk
    market:
      ChatID: '-822604829'
      Token: 5707736965:AAGV6ns6Ks3H7p4jXkkakFWh5AZRzFU-LgE
    tron:
      ChatID: '-1001804999261'
      Token: 5494595946:AAHNiVdjRx_JEMD3Hev4Zq2TWwMvaBDUFxo
  TronWallet:
    ChatID: '-1001808281551'
    Token: 5365942464:AAE3V9HFVJHVVyICcvCshRCA7jJjDdlAKnc
  VerifySystem:
    Host: 127.0.0.1
    Port: '8087'
    Token: 5836610069:AAEjs2fIVxInufJe3SGcfUWE3A657eGg2k8
    SupportChatID1: '-1001832120520'
    SupportChatID2: '-756886268'
    SupportChatID3: '-833006048'
    SupportChatID4: '-879945704'
  Treasury:
    ChatID: '-1001760998928'
    Token: 5765106932:AAGXmD4BOIF972y6els7ukggfdd7Remaq_E
  Logging:
    ChatID: '-1001760998928'
    Token: 5757403943:AAGNAlPE-d5ONUXt2zvxHTaHXBqjJmd9yRg
Postgres:
  Host: 159.69.93.63
  Port: '5432'
  User: root
  Password: jqnqMV6tFaOy3kd7ZlV8lRmS4oXgq7
  DBName: alnex_db
  SSLMode: disable
  PGDriver: pgx
  settings:
    MaxOpenConns: 60
    ConnMaxLifetime: 120
    MaxIdleConns: 30
    ConnMaxIdleTime: 20
RegistrationSystem:
  UserTokenLifetime: 7200
  ClientTokenLifetime: 7200
  SellerAgentTokenLifetime: 7200
RabbitMQ:
  Host: 127.0.0.1
  Port: '5672'
  User: guest
  Password: guest
  ErrorExchangeName: errors
  TronWalletExchangeName: tron_wallet
  NotificationExchangeName: notifications
  TreasuryExchangeName: treasury
  LoggingExchangeName: logging
Logger:
  Level: 1